services:

  auth-db:
    image: mariadb:11.1
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=auth
      - MARIADB_USER=auth
      - MARIADB_PASSWORD=password
    ports:
      - 3306:3306

  auth-cache:
    image: redis/redis-stack
    ports:
      - 6379:6379

  auth-service:
    depends_on:
      - auth-db
      - auth-cache
    image: anazworth/auth-service:latest
    ports:
      - 8080:8080
    environment:
      - MARIADB_URL=jdbc:mariadb://auth-db/auth
      - MARIADB_USERNAME=root
      - MARIADB_PASSWORD=rootpassword
      - REDIS_HOST=auth-cache

