FROM golang:1.20.4-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV ENVIRONMENT=production MONGO_URI=mongodb://readapiadmin:adminpassword@read-db:27017 DB=posts REDIS_URI=post-cache:6379 REDIS_PASSWORD=adminpassword
RUN go build -ldflags="-s -w" -o server .

FROM scratch

COPY --from=builder ["/build/server", "/build/.env", "/"]

EXPOSE 8081

ENTRYPOINT ["/server"]

