micronaut:
  application:
    name: feed_api
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  server:
    port: 8084
    cors:
      enabled: true
      configurations:
        cors:
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true
          max-age: 1800
datasources:
  default:
#    driver-class-name: org.h2.Driver
#    schema-generate: CREATE_DROP
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3308/posts
#    username: feedservice
#    password: feedpassword

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration/
#      validate-migration-naming: true

netty:
  default:
    allocator:
      max-order: 3
redis.uri: redis://localhost

rabbitmq:
  uri: amqp://localhost:5672